name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6

      - name: Configure npm auth for GitHub Packages
        run: |
          echo "@GabrielleMi:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.UTILS_PACKAGE_TOKEN }}

      - name: Install, build, and upload your site
        uses: withastro/action@v6
        env:
          NPM_TOKEN: ${{ secrets.UTILS_PACKAGE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.UTILS_PACKAGE_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4